--------------------------------------------------------------------------------
-- file generated by generate_weights.py
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.types.all;

package weights is

    constant num_weights      : integer := 8;
    constant weight_precision : integer := 10;

    constant W : complex_vector(0 to 7) := (
            (to_signed(1024, word_size), to_signed(0, word_size)),
            (to_signed(946, word_size), to_signed(392, word_size)),
            (to_signed(724, word_size), to_signed(724, word_size)),
            (to_signed(392, word_size), to_signed(946, word_size)),
            (to_signed(0, word_size), to_signed(1024, word_size)),
            (to_signed(-392, word_size), to_signed(946, word_size)),
            (to_signed(-724, word_size), to_signed(724, word_size)),
            (to_signed(-946, word_size), to_signed(392, word_size))
        );

end package weights;
